language: python
python:
    - "2.7"
    - "3.5"
install:
    - pip install -r test-requirements.txt
    - python setup.py develop
script: make coveralls
notifications:
    email: florian.pourtugau@hotmail.fr
